### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by cdgco** [cdgco/HestiaWebInterface#1]
Everything from VestaCP has been converted over to HestiaCP, however there are a number of HestiaCP specific features that still need to be implimented in HWI including: 

- [ ] Automatic HTTP-to-HTTPS Redirection Support
- [ ] HTTP Strict Transport Security Support
- [ ] PHP-FPM Backend Templates / Multi-PHP Support
- [ ] Mail Domain SSL Support
- [ ] Two-Factor Authentication Support
- [ ] Quick Install App Support
- [x] Open Web Domain Button
- [x] Domain Specific Webmail URLs

**Comment by kgnfth** [comment]
demo page does nt log you in

**Comment by cdgco** [comment]
@kgnfth Sorry, one of our servers died yesterday and I thought I got everything back online, but apparently the demos needed to be fixed. You should be able to log in now. Thanks for letting me know!

**Comment by cdgco** [comment]
@DanialNikbin While there isn't built-in integration to the file manager yet, you can install the [vwi-ftp](https://github.com/cdgco/vwi-ftp) plugin to add a WebFTP client to your control panel in the mean time.

**Comment by DanialNikbin** [comment]
Can I use it for Hestia? HestiaCP itself has a simple builtin file manager.

**Comment by cdgco** [comment]
Just glancing at the files before I actually test it, it looks like it should work perfectly.

The other temporary option if you would like to use the built in file manager would be to set the file manager link `https://DOMAIN:8083/fm/` as your FTP client url in the HWI settings, then it will show up in the apps section of the menu. This however is not great as the integration is not seamless and requires second authentication.

I will test the plugin and look into building integration with the file manager, however, syncing user authentication between the front end of both control panels can be tricky so it may not be done for some time.

**Comment by cdgco** [comment]
@DanialNikbin Looks like the WebFTP plugin works as long as you change the line `$ftpHost = VESTA_HOST_ADDRESS;` to `$ftpHost = HESTIA_HOST_ADDRESS;` at the top of the `ftp/ftp.php` file in the plugin

**Comment by DanialNikbin** [comment]
Yeah worked with that. Would be great if you could make a file manager that also supports online file editing and adding it to the sidebar menu.

**Comment by cdgco** [comment]
@DanialNikbin The plugin does support online editing for a user defined list of files, which by default are `"asp,ashx,asmx,aspx,asx,axd,cfm,cgi,css,html,htm,jhtml,js,php,phtml,pl,txt,xhtml,htaccess,log,crt,key,less,scss,md,sql,json"`, but I will work on integrating the built in file manager.

**Comment by cdgco** [comment]
It may not be apparent at first, the edit button is under the right click context menu for compatible files.

**Comment by DanialNikbin** [comment]
I see, perfect. Does it support zipping and unzipping?

**Comment by cdgco** [comment]
No. While it does download folders and groups of files as zips, there is no built in zip / unzip function.

**Comment by DanialNikbin** [comment]
I think the best option for HWI is to integrate it with HestaCP builtin file manager. It has the main features and it's design is also nice.

**Comment by cdgco** [comment]
@DanialNikbin I just ported over the File Manager into a plugin for HWI available [here](https://github.com/cdgco/hwi-fm). There are some small changes I plan to make in the future, and I just finished writing this, so let me know if you run into any problems.

**Comment by DanialNikbin** [comment]
I just installed it but there is a problem, when I login in file manager it says Folder not writable: /private/logs/

**Comment by cdgco** [comment]
@DanialNikbin Sorry, I realized after I went to bed last night that I forgot to update the instructions. 

In order to give the server write permissions, you need to use the following command `chmod -R 755 plugins/fm/{private,repository}` and possibly the command `chown -R USERNAME:USERNAME /home/admin/web` where `USERNAME` is the name of the account that owns the domain if you are hosting HWI on a HestiaCP server.

**Comment by DanialNikbin** [comment]
Yeah worked thanks. Can we make this file manager as a primary option and not under apps?

**Comment by cdgco** [comment]
I can move it to a different section in the menu, but seeing as it's an external app, I feel like it makes sense to place it under apps.

**Comment by DanialNikbin** [comment]
I would appreciate if you tell me how to add it as a primary menu.

**Comment by cdgco** [comment]
There is currently no system in place to accomplish that. You can edit the `manifest.xml` file in the fm directory and change `section` to `apps`, `administration`, or `account`, but there is no option to add it to the primary menu. That would require an update of HWI and the entire plugin system, not just the plugin itself.

**Comment by DanialNikbin** [comment]
I see. If I want to add the menu manually by code which file should I edit?

**Comment by cdgco** [comment]
The menu is generated in the `includes/includes.php` file under the function `primaryMenu($l4, $l5, $a2)` where `$l5` is the path to the root of HWI.

**Comment by DanialNikbin** [comment]
I'm trying to make the fm auto login. The problem is getting the user password.

**Comment by cdgco** [comment]
Any connection to the HestiaCP filesystem requires active authentication. If you are the only one using the file manager, and don't care about storing your password in plain text, you could define the password in `fm/configuration.php` as `$ftp_cred` and access the file manager directly at `/fm/app/`, but I do not reccommend that, as the current configuration uses multiple levels of encryption and active authorization which would be bypassed.

**Comment by DanialNikbin** [comment]
Thanks I may implement something else for that, will let you know. The file manager editor has a weird issue, when I edit a file it opens it by appending 4 new lines.

**Comment by cdgco** [comment]
I'll take a look, but I wasn't experiencing that yesterday, and I used the exact same package and version that HestiaCP uses for their file manager.

**Comment by cdgco** [comment]
I noticed that my system is prepending files with 2 lines. I updated the package and tried editing the configuration but coundn't find any solution. I believe it may have something to do with the file server and client using different connection methods, but I have contacted the package maintainer to see if they have a solution.

**Comment by DanialNikbin** [comment]
I found a bug on chrome. I'm unable to login to HWI using google chrome, when I press login button it returns to login page again. It maybe a session problem.

**Comment by cdgco** [comment]
Try changing `session_set_cookie_params(['samesite' => 'none']);` to `ini_set('session.cookie_samesite', 'None');` at the top of `login.php` and seeing if that works. If that doesn't work, try removing the `samesite` tag altogether.

Chrome changed the default cookie values this year and I believe there's a PHP bug with the way it handles setting cookie paramaters. I had seen this issue once before but hadn't taken the time to dive into it yet.

**Comment by DanialNikbin** [comment]
Removing that tag solved the issue.

**Comment by cdgco** [comment]
Hopefully that tag only needs to be changed on the login page, but I'll add that to the next update. Are you using PHP 7.3+ by the way? From what I can see this bug is only present in those versions.

**Comment by DanialNikbin** [comment]
Yeah I'm using php 7.4

**Comment by cdgco** [comment]
@DanialNikbin I just released a [new version](https://github.com/cdgco/vh-fm/releases/tag/v1.0) of the file manager plugin which fixes the new line error.

I have also updated HWI to fix the errors with PHP-FPM and PHP 7.3+ although I have not published a release package yet.

**Comment by DanialNikbin** [comment]
@cdgco Does Let's Encrypt auto SSL work?
